[project]
name = "project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
  "pandas==2.2.3",
  "openai==1.78.1",
  "python-dotenv==1.1.0",
  "pytest>=8.4.1",
  "pydantic>=2.11.7",
]
